export const ROUTES = {
  HOME: "/",
  // MAINHOME:"/discountit",
  ABOUT:"/about ",
  PRODUCT: `/products`,
  CATEGORIES: `/categories`,
  CATEGORY: `/category`,
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  POLICY: "/privacy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  ACCOUNT: "/my-account",
  ORDERS: "/my-account/orders",
  ACCOUNT_DETAILS: "/my-account/account-details",
  CHANGE_PASSWORD: "/my-account/change-password",
  WISHLIST: "/my-account/wishlist",
  SHIPPING_ADDRESS: "/my-account/shipping-address",
  SHOP: "/shop",
  // LOGIN: "/signin",
  // SIGN_UP: "/signup",
  SEARCH: "/search",
  ORDER: "/order",
};
